### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by AgentMax05** [AgentMax05/cpp_chess_bot#5]
### Things to Add

- [ ] Finish value_board function and add more ways to value a board
- [ ] Add pawn promotion when pawn reaches top or bottom rank
- [x] Check for squares that the kings attack in set_attacking
- [ ] Add castling for both black and white
- [ ] Add En passant move for pawns (https://en.wikipedia.org/wiki/En_passant)
- [x] Check for checkmate and stalemate
- [ ] Implement UCI Protocol

### Bugs

- [ ] Calling best_move with black sometimes returns a blank board (all zeros)

### Improvements

- [ ] Increase speed by searching most promising moves first
